# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


variables:
  - group: CheckmarxCredentials  # References your variable group   # BuildprojectName
  - name: projectName
    value: 'NewTestprojectexploitablepath'
  - name: System.Debug
    value: true  # ← Enable debug logging for sca resolver

steps:

- task: Application security testing@2026
  displayName: Running Checkmarx CxSAST scanning
  inputs:
    projectName: '$(projectName)'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'CxSASTconnectionnew'
    enableSastBranching: false
    preset: 'All'
    fullTeamName: 'CxServer'
    overrideProjectSettings: true
    fullScansScheduled: true
    fullScanCycle: '99' # After how many incremental scans you want to enable full scan
    comment: 'Scan-Origin - Azure DevOps, Branch - $(Build.SourceBranchName)' #Comments will reflect in the cxsast scans for placeholders and filters
    vulnerabilityThreshold: true
    failBuildForNewVulnerabilitiesEnabled: false
    failBuildForNewVulnerabilitiesSeverity: 'CRITICAL'
    critical: '300'
    high: '10'
    medium: '10'
    low: '10'
    enableDependencyScan: false
 
#******The below Dowloading and extract SCA Resolver is optional if your agent already has an SCA path available *******
- task: CmdLine@2
  displayName: Downloading and extract SCA Resolver
  inputs:
    script: |
      echo ---------- Downloading and installing SCA Resolver ----------
      curl -L https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz -o ScaResolver-linux64.tar.gz
      tar -xvf ScaResolver-linux64.tar.gz
      rm ScaResolver-linux64.tar.gz
      chmod +x ScaResolver
      ls -l
#************************************************************** 

# - task: Checkmarx AST@3
#   inputs:
#     CheckmarxService: 'Cx_Prajwal_PS'
#     projectName: '$(Build.Repository.Name)'
#     branchName: '$(Build.SourceBranchName)'
#     tenantName: '5twda'
#     additionalParams: '--scan-types "sast"'
  
# - task: Checkmarx AST@3
#   inputs:
#     CheckmarxService: 'CX_Auth_details'
#     projectName: '$(Build.Repository.Name)'
#     branchName: '$(Build.SourceBranchName)'
#     tenantName: 'sdsdfsef'
#     additionalParams: '--scan-types "sca" --sca-resolver "C:\Tools\ScaResolver\ScaResolver-win64 (3)\ScaResolver.exe" --sca-resolver-params "--log-level 'Debug' --extract-depth 10 --extract-archives zip --disable-delta-scan  --proxies proxyurl:port "'

# - task: Building dependencies 
#   input: 
#     script: "mvn clean install -U"    
- task: Application security testing@2026
  displayName: Running SCA using SCA Resolver
  inputs:
    projectName: '$(projectName)'
    enableProxy: false
    enableSastScan: false
    enableDependencyScan: true
    dependencyServerURL: 'CXSCACHAMPION'
    scaTeam: '/Champions'

  ## Only required when you need exploitable path  
    isEnableScaResolver: true
    pathToScaResolver: '$(Build.SourcesDirectory)'
    scaResolverAddParameters: '-s $(Build.SourcesDirectory) -n $(projectName)  -r scaResults/results.json --sast-result-path sastResults/results.json --cxuser $(sastUsername) --cxserver $(sastUrl) --cxpassword $(sastPassword) --cxprojectname $(projectName)  --log-level Debug'